name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-cs-fixer:
    name: "Lint & Analyse"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: 8.0
          version: 2
      - name: "PHP-CS-Fixer"
        run: vendor/bin/php-cs-fixer fix --dry-run
      - name: "PSalm"
        run: vendor/bin/psalm --show-info=true
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: 8.2
          memory_limit: 1024M
          version: 9
          testsuite: Unit
          bootstrap: vendor/autoload.php
